### ISSUE TITLE
Help button does not work in Firefox

### ISSUE THREAD

**Issue by Talkless** [waymarkedtrails/waymarkedtrails-website#3]
If I click "?" button in https://hiking.waymarkedtrails.org browser console prints this error:
```
Uncaught (in promise) TypeError: t[0][t[4].section] is undefined
    $m PanelHelp.svelte:139
    Rm PanelHelp.svelte:138
    p PanelHelp.svelte:136
    te index.mjs:1085
    ee index.mjs:1052
    promise callback*he index.mjs:1010
    ctx index.mjs:1868
    Fm PanelHelp.svelte:31
    r index.mjs:18
    me index.mjs:1802
    ee index.mjs:1067
    promise callback*he index.mjs:1010
    ctx index.mjs:1868
    Qm App.svelte:29
    s index.mjs:34
    Bn app_state.js:17
    pf Footer.svelte:53
    V index.mjs:996
    V index.mjs:996
    Up ButtonFooter.svelte:2
    S index.mjs:412
    m ButtonFooter.svelte:5
    me index.mjs:1798
    m Footer.svelte:50
    me index.mjs:1798
    m App.svelte:64
    p App.svelte:59
    te index.mjs:1085
    ee index.mjs:1052
    promise callback*he index.mjs:1010
    ctx index.mjs:1868
    Qm App.svelte:59
    s index.mjs:34
    set runtime.esm.js:15
    set runtime.esm.js:15
    <anonymous> runtime.esm.js:15
    <anonymous> i18n.js:28
PanelHelp.svelte:139:82
    $m PanelHelp.svelte:139
    Rm PanelHelp.svelte:138
    p PanelHelp.svelte:136
    te index.mjs:1085
    ee index.mjs:1052
    (Async: promise callback)
    he index.mjs:1010
    ctx index.mjs:1868
    Fm PanelHelp.svelte:31
    AsyncFunctionNext self-hosted:632
    (Async: async)
    r index.mjs:18
    map self-hosted:180
    me index.mjs:1802
    ee index.mjs:1067
    (Async: promise callback)
    he index.mjs:1010
    ctx index.mjs:1868
    Qm App.svelte:29
    s index.mjs:34
    Bn app_state.js:17
    pf Footer.svelte:53
    V index.mjs:996
    forEach self-hosted:164
    V index.mjs:996
    Up ButtonFooter.svelte:2
    (Async: EventListener.handleEvent)
    S index.mjs:412
    m ButtonFooter.svelte:5
    me index.mjs:1798
    m Footer.svelte:50
    me index.mjs:1798
    m App.svelte:64
    p App.svelte:59
    te index.mjs:1085
    ee index.mjs:1052
    (Async: promise callback)
    he index.mjs:1010
    ctx index.mjs:1868
    Qm App.svelte:59
    s index.mjs:34
    set runtime.esm.js:15
    thenFinally self-hosted:2683
    (Async: promise callback)
    finally self-hosted:2672
    set runtime.esm.js:15
    <anonymous> runtime.esm.js:15
    <anonymous> i18n.js:28
    InnerModuleEvaluation self-hosted:2355
    InnerModuleEvaluation self-hosted:2355
    evaluation self-hosted:2312

```
Clicking makes two vertical lines appear, and background becomes a bit darker, but nothing of use is shown.
Firefox 102.0.1 on Debian Sid.

**Comment by lonvia** [comment]
Works for me with Firefox 102.0.1. Please try a Shift+Reload of the site.

**Comment by Talkless** [comment]
Reloading does not help. Even private browsing mode does not help. But it works in Debian Sid VM...

Not sure why "Private" browsing mode does nothing... Is there some state, LocalStorage, that is still available in private browsing?

I guess I need to clear all browser caches from within settings, but gonna lose all these tabs...

**Comment by lonvia** [comment]
What are your language settings, i.e. what AcceptLanguage header is sent by your browser? Have you configured a custom language in the settings panel of waymarkedtrails?

**Comment by Talkless** [comment]
My browser has Lithuanian as main laguage I guess:

```
GET / HTTP/2
Host: hiking.waymarkedtrails.org
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
Accept-Language: lt,en-US;q=0.8,en;q=0.6,ru;q=0.4,pl;q=0.2
Accept-Encoding: gzip, deflate, br
DNT: 1
Connection: keep-alive
Upgrade-Insecure-Requests: 1
Sec-Fetch-Dest: document
Sec-Fetch-Mode: navigate
Sec-Fetch-Site: none
Sec-Fetch-User: ?1
Sec-GPC: 1
```

**Comment by lonvia** [comment]
Yep, that's the problem. When I switch to Lithuanian, I can reproduce both your issues on any browser. Fix will follow.

**Comment by lonvia** [comment]
Fixed in https://github.com/waymarkedtrails/waymarkedtrails-website/commit/0d35342bea1337afd9ad0404eec7554d2488d237

**Comment by Talkless** [comment]
Thanks @lonvia ! Help does work now, though osmc preview is still broken for me.
